# TCL File Generated by Component Editor 16.1
# Wed Dec 12 18:47:51 GMT+08:00 2018
# DO NOT MODIFY


# 
# CPAdderRouter "CPAdderRouter" v1.0
# CNLHC 2018.12.12.18:47:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module CPAdderRouter
# 
set_module_property DESCRIPTION ""
set_module_property NAME CPAdderRouter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC/OFDMCPAdder
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME CPAdderRouter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL OFDM_Cyclic_Prefix_Adder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file OFDM_Cyclic_Prefix_Adder.v VERILOG PATH OFDM_Cyclic_Prefix_Adder.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter Packet_Length POSITIVE 1024 ""
set_parameter_property Packet_Length DEFAULT_VALUE 1024
set_parameter_property Packet_Length DISPLAY_NAME Packet_Length
set_parameter_property Packet_Length WIDTH ""
set_parameter_property Packet_Length TYPE POSITIVE
set_parameter_property Packet_Length UNITS None
set_parameter_property Packet_Length ALLOWED_RANGES 1:2147483647
set_parameter_property Packet_Length DESCRIPTION ""
set_parameter_property Packet_Length AFFECTS_GENERATION false
set_parameter_property Packet_Length HDL_PARAMETER true

add_parameter CP_Length POSITIVE 128 ""
set_parameter_property CP_Length DEFAULT_VALUE 128
set_parameter_property CP_Length DISPLAY_NAME CP_Length
set_parameter_property CP_Length WIDTH ""
set_parameter_property CP_Length TYPE POSITIVE
set_parameter_property CP_Length UNITS None
set_parameter_property CP_Length ALLOWED_RANGES 1:2147483647
set_parameter_property CP_Length DESCRIPTION ""
set_parameter_property CP_Length AFFECTS_GENERATION false
set_parameter_property CP_Length HDL_PARAMETER true


# 
# display items
# 


# 
# connection point asi_in0
# 
add_interface asi_in0 avalon_streaming end
set_interface_property asi_in0 associatedClock clock
set_interface_property asi_in0 associatedReset reset
set_interface_property asi_in0 dataBitsPerSymbol 22
set_interface_property asi_in0 errorDescriptor ""
set_interface_property asi_in0 firstSymbolInHighOrderBits true
set_interface_property asi_in0 maxChannel 0
set_interface_property asi_in0 readyLatency 0
set_interface_property asi_in0 ENABLED true
set_interface_property asi_in0 EXPORT_OF ""
set_interface_property asi_in0 PORT_NAME_MAP ""
set_interface_property asi_in0 CMSIS_SVD_VARIABLES ""
set_interface_property asi_in0 SVD_ADDRESS_GROUP ""

add_interface_port asi_in0 asi_in0_data data Input 22
add_interface_port asi_in0 asi_in0_valid valid Input 1
add_interface_port asi_in0 asi_in0_endofpacket endofpacket Input 1
add_interface_port asi_in0 asi_in0_startofpacket startofpacket Input 1
add_interface_port asi_in0 asi_in0_ready ready Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point buffer_in
# 
add_interface buffer_in avalon_streaming end
set_interface_property buffer_in associatedClock clock
set_interface_property buffer_in associatedReset reset
set_interface_property buffer_in dataBitsPerSymbol 22
set_interface_property buffer_in errorDescriptor ""
set_interface_property buffer_in firstSymbolInHighOrderBits true
set_interface_property buffer_in maxChannel 0
set_interface_property buffer_in readyLatency 0
set_interface_property buffer_in ENABLED true
set_interface_property buffer_in EXPORT_OF ""
set_interface_property buffer_in PORT_NAME_MAP ""
set_interface_property buffer_in CMSIS_SVD_VARIABLES ""
set_interface_property buffer_in SVD_ADDRESS_GROUP ""

add_interface_port buffer_in buffer_in_data data Input 22
add_interface_port buffer_in buffer_in_ready ready Output 1
add_interface_port buffer_in buffer_in_valid valid Input 1
add_interface_port buffer_in buffer_in_startofpacket startofpacket Input 1
add_interface_port buffer_in buffer_in_endofpacket endofpacket Input 1


# 
# connection point data_out
# 
add_interface data_out avalon_streaming start
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset reset
set_interface_property data_out dataBitsPerSymbol 22
set_interface_property data_out errorDescriptor ""
set_interface_property data_out firstSymbolInHighOrderBits true
set_interface_property data_out maxChannel 0
set_interface_property data_out readyLatency 0
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_out_data data Output 22
add_interface_port data_out data_out_valid valid Output 1
add_interface_port data_out data_out_error error Output 2
add_interface_port data_out data_out_endofpacket endofpacket Output 1
add_interface_port data_out data_out_startofpacket startofpacket Output 1


