# TCL File Generated by Component Editor 16.1
# Wed Dec 12 21:52:18 GMT+08:00 2018
# DO NOT MODIFY


# 
# Avalon_ST_Demux "Avalon ST Demux" v1.0
# CNLHC 2018.12.12.21:52:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_ST_Demux
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avalon_ST_Demux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC/utility
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME "Avalon ST Demux"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Avalon_ST_Demux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Avalon_ST_Demux.v VERILOG PATH Avalon_ST_Demux.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point asi_in0
# 
add_interface asi_in0 avalon_streaming end
set_interface_property asi_in0 associatedClock clock
set_interface_property asi_in0 associatedReset reset
set_interface_property asi_in0 dataBitsPerSymbol 22
set_interface_property asi_in0 errorDescriptor ""
set_interface_property asi_in0 firstSymbolInHighOrderBits true
set_interface_property asi_in0 maxChannel 0
set_interface_property asi_in0 readyLatency 0
set_interface_property asi_in0 ENABLED true
set_interface_property asi_in0 EXPORT_OF ""
set_interface_property asi_in0 PORT_NAME_MAP ""
set_interface_property asi_in0 CMSIS_SVD_VARIABLES ""
set_interface_property asi_in0 SVD_ADDRESS_GROUP ""

add_interface_port asi_in0 asi_in0_data data Input 22
add_interface_port asi_in0 asi_in0_ready ready Output 1
add_interface_port asi_in0 asi_in0_valid valid Input 1
add_interface_port asi_in0 asi_in0_endofpacket endofpacket Input 1
add_interface_port asi_in0 asi_in0_startofpacket startofpacket Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point aso_out0
# 
add_interface aso_out0 avalon_streaming start
set_interface_property aso_out0 associatedClock clock
set_interface_property aso_out0 associatedReset reset
set_interface_property aso_out0 dataBitsPerSymbol 22
set_interface_property aso_out0 errorDescriptor ""
set_interface_property aso_out0 firstSymbolInHighOrderBits true
set_interface_property aso_out0 maxChannel 0
set_interface_property aso_out0 readyLatency 0
set_interface_property aso_out0 ENABLED true
set_interface_property aso_out0 EXPORT_OF ""
set_interface_property aso_out0 PORT_NAME_MAP ""
set_interface_property aso_out0 CMSIS_SVD_VARIABLES ""
set_interface_property aso_out0 SVD_ADDRESS_GROUP ""

add_interface_port aso_out0 aso_out0_data data Output 22
add_interface_port aso_out0 aso_out0_ready ready Input 1
add_interface_port aso_out0 aso_out0_valid valid Output 1
add_interface_port aso_out0 aso_out0_endofpacket endofpacket Output 1
add_interface_port aso_out0 aso_out0_startofpacket startofpacket Output 1


# 
# connection point aso_out1
# 
add_interface aso_out1 avalon_streaming start
set_interface_property aso_out1 associatedClock clock
set_interface_property aso_out1 associatedReset reset
set_interface_property aso_out1 dataBitsPerSymbol 22
set_interface_property aso_out1 errorDescriptor ""
set_interface_property aso_out1 firstSymbolInHighOrderBits true
set_interface_property aso_out1 maxChannel 0
set_interface_property aso_out1 readyLatency 0
set_interface_property aso_out1 ENABLED true
set_interface_property aso_out1 EXPORT_OF ""
set_interface_property aso_out1 PORT_NAME_MAP ""
set_interface_property aso_out1 CMSIS_SVD_VARIABLES ""
set_interface_property aso_out1 SVD_ADDRESS_GROUP ""

add_interface_port aso_out1 aso_out1_data data Output 22
add_interface_port aso_out1 aso_out1_ready ready Input 1
add_interface_port aso_out1 aso_out1_valid valid Output 1
add_interface_port aso_out1 aso_out1_endofpacket endofpacket Output 1
add_interface_port aso_out1 aso_out1_startofpacket startofpacket Output 1

