# TCL File Generated by Component Editor 18.0
# Sat Dec 08 10:47:57 GMT+08:00 2018
# DO NOT MODIFY


# 
# Fix_Length_Bytes2Packets "Fix Length Bytes To Packet" v1.0
# CNLHC 2018.12.08.10:47:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Fix_Length_Bytes2Packets
# 
set_module_property DESCRIPTION ""
set_module_property NAME Fix_Length_Bytes2Packets
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME "Fix Length Bytes To Packet"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Fix_Length_Bytes2Packets
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Fix_Length_Bytes2Packets.v VERILOG PATH Fix_Length_Bytes2Packets.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point asi_in0
# 
add_interface asi_in0 avalon_streaming end
set_interface_property asi_in0 associatedClock clock_1
set_interface_property asi_in0 associatedReset reset
set_interface_property asi_in0 dataBitsPerSymbol 8
set_interface_property asi_in0 errorDescriptor ""
set_interface_property asi_in0 firstSymbolInHighOrderBits true
set_interface_property asi_in0 maxChannel 0
set_interface_property asi_in0 readyLatency 0
set_interface_property asi_in0 ENABLED true
set_interface_property asi_in0 EXPORT_OF ""
set_interface_property asi_in0 PORT_NAME_MAP ""
set_interface_property asi_in0 CMSIS_SVD_VARIABLES ""
set_interface_property asi_in0 SVD_ADDRESS_GROUP ""

add_interface_port asi_in0 asi_in0_data data Input 8
add_interface_port asi_in0 asi_in0_ready ready Output 1
add_interface_port asi_in0 asi_in0_valid valid Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_1
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point aso_out0
# 
add_interface aso_out0 avalon_streaming start
set_interface_property aso_out0 associatedClock clock_1
set_interface_property aso_out0 associatedReset reset
set_interface_property aso_out0 dataBitsPerSymbol 2
set_interface_property aso_out0 errorDescriptor ""
set_interface_property aso_out0 firstSymbolInHighOrderBits true
set_interface_property aso_out0 maxChannel 0
set_interface_property aso_out0 readyLatency 0
set_interface_property aso_out0 ENABLED true
set_interface_property aso_out0 EXPORT_OF ""
set_interface_property aso_out0 PORT_NAME_MAP ""
set_interface_property aso_out0 CMSIS_SVD_VARIABLES ""
set_interface_property aso_out0 SVD_ADDRESS_GROUP ""

add_interface_port aso_out0 aso_out0_data data Output 32
add_interface_port aso_out0 aso_out0_ready ready Input 1
add_interface_port aso_out0 aso_out0_valid valid Output 1
add_interface_port aso_out0 aso_out0_startofpacket startofpacket Output 1
add_interface_port aso_out0 aso_out0_endofpacket endofpacket Output 1
add_interface_port aso_out0 aso_out0_empty empty Output 4


# 
# connection point clock_1
# 
add_interface clock_1 clock end
set_interface_property clock_1 clockRate 0
set_interface_property clock_1 ENABLED true
set_interface_property clock_1 EXPORT_OF ""
set_interface_property clock_1 PORT_NAME_MAP ""
set_interface_property clock_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_1 clock_clk clk Input 1



